name: Maven Build and Deploy

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - '**/v**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Extract version number
      id: extract-version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build and Install with Maven
      run: |
        echo "------- Maven Install -------";
        mvn -B -e -f pom.xml clean install

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: websockets-lex
        path: target/*.lex

    - name: Checkout Lucee
      uses: actions/checkout@v4
      with:
        repository: lucee/lucee
        path: lucee

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Run Lucee Test Suite
      uses: lucee/script-runner@main
      with:
        webroot: ${{ github.workspace }}/lucee/test
        execute: /bootstrap-tests.cfm
        luceeVersionQuery: 6.2/stable/zero
        extensionDir: ${{ github.workspace }}/target
      env:
        testLabels: websocket
        testAdditional: ${{ github.workspace }}/tests

  build:
    runs-on: ubuntu-latest
    env:
      DO_DEPLOY: "${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/master') }}"
    needs: [ test ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Extract version number
        id: extract-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Build and Deploy with Maven
        if: ${{ env.DO_DEPLOY }}
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          if [[ "$VERSION" == *-SNAPSHOT ]]; then
            echo "------- Maven Deploy snapshot on ${{ github.event_name }} -------";
            mvn -B -e -f pom.xml clean deploy --settings maven-settings.xml
          else
            echo "------- Maven Deploy release on ${{ github.event_name }} -------";
            mvn -B -e -f pom.xml clean deploy -DperformRelease=true --settings maven-settings.xml
          fi

